sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - ghc
go:
  - tip
install:
  - nvm install stable
  - nvm use stable
  - npm install ffi glob
  - gem install ffi
script:
  - cargo build
  - cd c && gcc main.c -L ../target/debug -lstringtools -o main && LD_LIBRARY_PATH=../target/debug ./main
  - cd ../haskell && ghc --make main.hs -L../target/debug -lstringtools -o main && LD_LIBRARY_PATH=../target/debug ./main
  - cd ../go && LD_LIBRARY_PATH=../target/debug go run main.go
  - cd ../python && python main.py
  - cd ../node && node main.js
  - cd ../ruby && ruby main.rb
