sudo: false
language: rust
rust:
  - stable
  - nightly
install:
  - nvm install stable
  - nvm use stable
  - npm install ffi glob
  - gem install ffi
script:
  - cargo build
  - cd python && python main.py
  - cd ../node && node main.js
  - cd ../ruby && ruby main.rb
