sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - nvm install stable
  - nvm use stable
  - npm install ffi glob
  - gem install ffi
script:
  - make node
  - make python
  - make ruby
