language: rust
rust:
  - nightly
install:
  - curl https://raw.githubusercontent.com/creationix/nvm/v0.24.0/install.sh | bash
  - nvm install stable
  - nvm use stable
script:
  - cargo build
  - cd python && python main.py
  - cd node && node main.js
